Implement account creation flow
spine-examples/ChatSPN pull request #14
Opened 2023-03-22 22:47 UTC by Vladyslav-Kuksiuk

This PR adds an implementation of the account creation flow and adds the email address to the user.

Account creation flow model:
![image](https://user-images.githubusercontent.com/106074440/227054714-eb06d29d-20b8-4886-8ab7-02ea857cbae7.png)

2023-03-23 16:26 UTC, Artem-Semenov-dev commented on model/src/main/proto/spine_examples/chatspn/account/user_commands.proto
> +    AccountCreationId account_creation_process = 4 [(required) = true];
Maybe ```initiator``` is better here?

2023-03-23 16:43 UTC, Artem-Semenov-dev commented on server/src/test/java/io/spine/examples/chatspn/server/account/AccountCreationTest.java
> +class AccountCreationTest extends ContextAwareTest {
Looks `final` to me.

2023-03-23 17:14 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/chatspn/server/account/AccountCreationTest.java
> +    @DisplayName("emit `AccountCreated` event if the process is finished successfully and archive itself")
Fixed.

2023-03-24 14:25 UTC, armiol requested changes
@Vladyslav-Kuksiuk please see my comments.

2023-03-24 14:25 UTC, armiol commented on model/src/main/proto/spine_examples/chatspn/account/reserved_email_commands.proto
> +    AccountCreationId account_creation_process = 3 [(required) = true];
I would name this `process`, it's simple enough.

2023-03-24 14:25 UTC, armiol commented on server/src/test/java/io/spine/examples/chatspn/server/account/AccountCreationTest.java
> +        AccountCreated expectedEvent = AccountCreated
Could you please start extracting some of code devoted to signal creation, to the respective test environment?

2023-03-25 13:56 UTC, armiol approved these changes
LGTM.

2023-03-27 09:14 UTC, merged