Implement message removal flow
spine-examples/ChatSPN pull request #16
Opened 2023-03-28 11:04 UTC by Vladyslav-Kuksiuk

This PR adds an implementation of the message removal flow.

Message removal flow model:
![image](https://user-images.githubusercontent.com/106074440/228216389-205673a5-f4d1-4810-842a-2046ce70d486.png)

2023-03-28 11:51 UTC, Artem-Semenov-dev reviewed
Almost LGTM, please see my comment.

2023-03-28 11:51 UTC, Artem-Semenov-dev commented on server/src/main/java/io/spine/examples/chatspn/server/message/MessageAggregate.java
> +        if (!state().hasId() || state().getIsRemoved()) {
`getIsRemoved()` sounds weird to me. Consider renaming.

2023-03-29 10:56 UTC, armiol requested changes
Please see my comments.

2023-03-29 10:56 UTC, armiol commented on model/src/main/proto/spine_examples/chatspn/message/message.proto
> +    bool is_removed = 6 [(required) = true];
Can we just mark this aggregate as "deleted" instead?

2023-03-29 10:56 UTC, armiol commented on model/src/main/proto/spine_examples/chatspn/message/removal_events.proto
> +// The message failed to be removed.
Let's describe somewhere (maybe it's here?) what are the reasons for that. 

Right now there is no documentation explaining who can remove messages. Maybe, that's a command-level documentation. If we had such a place, we could reference it from the documentation of all related events and rejections.

2023-03-30 15:49 UTC, merged