Implement chat leaving flow
spine-examples/ChatSPN pull request #23
Opened 2023-04-19 13:05 UTC by Vladyslav-Kuksiuk

This PR adds an implementation of the chat leaving flow.

Chat leaving flow model:
![image](https://user-images.githubusercontent.com/106074440/233322634-43e26c6d-73d4-48c7-8270-baf5419b087a.png)

2023-04-19 13:35 UTC, Artem-Semenov-dev reviewed
@Vladyslav-Kuksiuk please see my comments.

2023-04-19 13:35 UTC, Artem-Semenov-dev commented on server/src/main/java/io/spine/examples/chatspn/server/chat/ChatAggregate.java
> +     *         or the user who told to delete group chat wasn't a chat owner / last member,
Please choose one style between '/' and 'or the'(it is below).

2023-04-19 13:35 UTC, Artem-Semenov-dev commented on server/src/main/java/io/spine/examples/chatspn/server/chat/ChatAggregate.java
> +    }
It looks weird to me. Please review.

2023-04-19 13:35 UTC, Artem-Semenov-dev commented on server/src/test/java/io/spine/examples/chatspn/server/chat/ChatTest.java
> +                    .isTrue();
Please adjust the code layout.

2023-04-19 13:35 UTC, Artem-Semenov-dev commented on model/src/main/proto/spine_examples/chatspn/chat/chat.proto
> +    repeated spine.core.UserId member = 2 [(distinct) = true];
I think if the member's list can be empty It should be described in the documentation. Please review.

2023-04-19 14:02 UTC, armiol requested changes
Please see my comments.

2023-04-19 14:02 UTC, armiol commented on server/src/test/java/io/spine/examples/chatspn/server/chat/given/ChatTestEnv.java
> +    public static LeaveChat leaveChatCommand(Chat chat, UserId user) {
Let's shorten to `leaveChat`.

2023-04-20 11:08 UTC, armiol approved these changes
@Vladyslav-Kuksiuk LGTM with some comments to address.

2023-04-20 15:08 UTC, merged