Add test on ChatSPN server
spine-examples/ChatSPN pull request #32
Opened 2023-05-25 20:13 UTC by Vladyslav-Kuksiuk

This PR provides tests on `ChatsSpnServer`  through an [issue with subscriptions](https://github.com/spine-examples/ChatSPN/issues/30).

2023-05-26 10:09 UTC, Artem-Semenov-dev reviewed
@Vladyslav-Kuksiuk almost LGTM. Please see my comments.

2023-05-26 10:09 UTC, Artem-Semenov-dev commented on server/src/test/java/io/spine/examples/chatspn/server/ChatSpnServerTest.java
> +    private static final int TEST_SERVER_PORT = DEFAULT_CLIENT_SERVICE_PORT;
I think it is redundant, you can just use `DEFAULT_CLIENT_SERVICE_PORT`.

2023-05-26 10:09 UTC, Artem-Semenov-dev commented on server/src/test/java/io/spine/examples/chatspn/server/ChatSpnServerTest.java
> +    Client createClient() {
It can be private.

2023-05-29 13:51 UTC, armiol requested changes
@Vladyslav-Kuksiuk please see my comments.

2023-05-29 13:51 UTC, armiol commented on server/src/test/java/io/spine/examples/chatspn/server/ChatSpnServerTest.java
> +    @DisplayName("handle command and request for projection status")
"Call a method and then call another method, receiving some Proto message is response"?

2023-05-29 13:51 UTC, armiol commented on server/src/test/java/io/spine/examples/chatspn/server/ChatSpnServerTest.java
> +    @DisplayName("handle subscription on entity")
Continuing my previous comment.

Let's speak in domain terms. I would also refrain from saying "handle" everywhere.

2023-05-29 15:11 UTC, armiol commented on server/src/test/java/io/spine/examples/chatspn/server/ChatSpnServerTest.java
> +            "in response to `QueryRequest` by the `UserProfile` class")
There is a space missing either here or in the previous line.

2023-05-29 15:13 UTC, armiol commented on server/src/test/java/io/spine/examples/chatspn/server/ChatSpnServerTest.java
> +            "will be emitted in response to the `CreateAccount` command")
"is emitted".

It's here and in other similar cases.

Please have a read on conditionals in English.

2023-06-02 09:29 UTC, merged