Implement a user profile modal window in the desktop client
spine-examples/ChatSPN pull request #36
Opened 2023-06-08 13:21 UTC by Vladyslav-Kuksiuk

This PR implements a user profile modal window in the desktop client.

Here are some usage scenarios:

- Search profile and create chat:
![Jdk-17 0 2 2023 06 06 - 14 20 13 09 (2)](https://github.com/spine-examples/ChatSPN/assets/106074440/cece3c30-726e-470d-af5e-da2101872c0b)

- Open profile by chat avatar and delete chat:
![Jdk-17 0 2 2023 06 06 - 14 20 13 09 (3)](https://github.com/spine-examples/ChatSPN/assets/106074440/29ecee2a-adee-49d7-9741-9602f5ec423d)

- Open your own profile and log out:
![Jdk-17 0 2 2023 06 06 - 14 20 13 09 (4)](https://github.com/spine-examples/ChatSPN/assets/106074440/56bb1b82-6662-41c4-92e5-18cdc15bb908)

2023-06-08 14:06 UTC, Artem-Semenov-dev reviewed
LGTM.

2023-06-09 12:50 UTC, armiol requested changes
General UI idea is to have less pop-ups, so that users would not have any blocking windows unless something important happens (payment, deletion, etc.).

Please have a look at other chats, and analyse how they implement similar functionality.

I am not reviewing the code changes now, because the approach in general should be different.

2023-06-22 13:48 UTC, Artem-Semenov-dev reviewed
@Vladyslav-Kuksiuk LGTM with a few comments.

2023-06-22 13:48 UTC, Artem-Semenov-dev commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/ChatsPage.kt
> +                    tint = MaterialTheme.colorScheme.primary
Please choose one style: write the parameters' name or not.

2023-06-22 13:48 UTC, Artem-Semenov-dev commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/ChatsPage.kt
> +    Box(Modifier.clip(RoundedCornerShape(8.dp))) {
I think we can extract this to `MaterialTheme` for more readability.

2023-06-22 13:48 UTC, Artem-Semenov-dev commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/ChatsPage.kt
> +private fun ChatMoreButton(model: ChatsPageModel, chat: ChatData) {
Do we need a `Chat` prefix here? Consider renaming.

2023-06-22 13:48 UTC, Artem-Semenov-dev commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/ChatsPage.kt
> + * Represents the text button.
I think this deserves better documentation.

2023-06-22 16:25 UTC, armiol requested changes
LGTM in general. But please see my comment. 

Also, let's not use any icons from existing commercial applications. We should be very careful about licensing. Right now some of the icons look very telegram-y.

2023-06-22 16:25 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/ChatsPage.kt
> +private fun ProfileTab(model: ChatsPageModel) {
I think, profiles should belong to their own Kotlin file. 

It's weird that they are a part of chats, even though at the moment these features are somewhat related in navigation.

2023-06-30 14:03 UTC, armiol requested changes
@Vladyslav-Kuksiuk mostly LGTM. Please see my comments.

2023-06-30 14:03 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/navigation/NavigationModel.kt
> +public data class ChatData(
With the documented purpose in mind, this name is too generic, especially for `public` data type.

2023-06-30 14:03 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/profile/ChatDeletionDialog.kt
> + * Representation of the chat deletion confirmation modal.
"A modal dialog allowing to delete some chat."

2023-06-30 14:03 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/profile/LogoutDialog.kt
> + * Returns a representation of the logout confirmation modal.
Can we please not use "represent" and its derivatives this often?

This word has many meanings, and is way too formal. Also, [this](https://constitutioncenter.org/blog/no-taxation-without-representation#:~:text=The%20Stamp%20Act%20Congress%20met,lacked%20representation%20in%20British%20Parliament.).

@Artem-Semenov-dev FYI.

2023-06-30 14:03 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/profile/LogoutDialog.kt
> + * Returns a representation of the logout confirmation modal.
"A modal dialog allowing the current user to log out."

2023-06-30 16:11 UTC, armiol requested changes

2023-06-30 16:11 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/navigation/NavigationModel.kt
> +public data class ChatData(
This is still too broad. Please rename more precisely.

And its documentation was fine.

2023-07-14 15:58 UTC, armiol approved these changes
@Vladyslav-Kuksiuk LGTM with some comments to address.

2023-07-14 15:58 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/Client.kt
> +     * When a success or failure event is emitted, subscriptions will be canceled.
"are cancelled"

Please DO have a read on English conditionals.

2023-07-14 15:58 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/navigation/NavigationModel.kt
> +     * @param userId id of the user to open profile
`ID`

Please do a case-sensitive search for "id" in the documentation.

2023-07-14 15:58 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/navigation/NavigationModel.kt
> +     * Opens a page with chat info. If the chat is personal, a user profile will be opened.
The first paragraph should always be a single sentence.

2023-07-14 15:58 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/chatspn/desktop/navigation/NavigationModel.kt
> + * @return found chat or `null` if chat is not found
"chat with the given ID, or `null` if ..."

2023-07-31 10:34 UTC, merged